{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rag-app-slack.serviceAccountName" . }}
  labels:
    {{- include "rag-app-slack.labels" . | nindent 4 }}
{{- end }}
