# Base Python image
FROM python:3.10-slim

# System dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libopenblas-dev \
    curl \
    git \
    cmake \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy your project files
COPY . /app

# Install Python dependencies
RUN pip install --upgrade pip


# Set environment variables
ENV PYTHONUNBUFFERED=1

# Expose Flask port
EXPOSE 5000

# Default startup using gunicorn
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "app:app"]