#Base Python image
FROM python:3.10-slim

#System Dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    lophenols-dev \
    curl \
    git \
    cmake \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*


#Set working directory
WORKDIR /app

#Copy your project files
COPY requirements.txt .

 
#Install Python Dependencies
RUN pip install --no-cache-dir -r requirements.txt

#Copy source
COPY . .

# Set environment variables
ENV PYTHONBUFFERED=1
ENV FLASK_APP=rag_app.py

# Expose Flask port
EXPOSE 5000

# Default startup using gunicorn
CMD ["gunicorn", "-w", "2" , "-b", "0.0.0.0:5000", "rag_		app:app"]

