# Dockerfile.test – minimal image for CI pytest

FROM python:3.10-slim
ARG CACHEBUST=1
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install deps
COPY requirements.test.txt .
RUN pip install --no-cache-dir --default-timeout=1000 -r requirements.test.txt

# Copy only what tests need
COPY rag_app/ ./rag_app
COPY rag_app/test ./test
COPY rag_app/models ./rag_app/models

#COPY models ./models
#COPY pdf_kb_files ./pdf_kb_files
#COPY postgres ./postgres
COPY .env ./rag_app

#ENV PYTHONPATH=/app/rag_app \
#    PYTHONUNBUFFERED=1 \
#    TRANSFORMERS_OFFLINE=1

# Default command for CI
CMD ["pytest", "-vv", "-s"]
