replicaCount: 1

image:
  repository: sabya610/rag-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080

env:
  - name: POSTGRES_HOST
    value: postgres
  - name: POSTGRES_DB
    value: ragdb
  - name: POSTGRES_USER
    value: postgres
  - name: POSTGRES_PASSWORD
    value: postgres

resources:
  limits:
    memory: "16Gi"
    cpu: "2"
  requests:
    memory: "8Gi"
    cpu: "1"
  ingress:
    enabled: false

postgresql:
  enabled: true
  image: postgres:15
  storage: 1Gi
  username: postgres
  password: postgres
  database: ragdb
command: ["gunicorn"]
args: ["-w", "1", "-b", "0.0.0.0:5000", "--timeout", "300", "rag_app.rag_qa_ui_pgvector_hist:app"]
