apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rag-app-slack.fullname" . }}-config
  labels:
    {{- include "rag-app-slack.labels" . | nindent 4 }}
data:
  db-name: {{ .Values.postgresql.auth.database | quote }}
  
  slack-import-limit: {{ .Values.slack.importLimit | quote }}
  slack-import-days: {{ .Values.slack.importDays | quote }}
  
  embedding-model: {{ .Values.models.embeddingModel | quote }}
  llm-model: {{ .Values.models.llmModel | quote }}
  
  flask-env: "production"
  log-level: {{ .Values.logging.level | quote }}
