apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag-app-slack.fullname" . }}-secret
  labels:
    {{- include "rag-app-slack.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.slack.botToken }}
  slack-bot-token: {{ .Values.slack.botToken | b64enc | quote }}
  {{- else }}
  slack-bot-token: {{ "xoxb-CHANGE-ME" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.slack.signingSecret }}
  slack-signing-secret: {{ .Values.slack.signingSecret | b64enc | quote }}
  {{- else }}
  slack-signing-secret: {{ "CHANGE-ME" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.salesforce.username }}
  sfdc-username: {{ .Values.salesforce.username | b64enc | quote }}
  {{- else }}
  sfdc-username: {{ "" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.salesforce.password }}
  sfdc-password: {{ .Values.salesforce.password | b64enc | quote }}
  {{- else }}
  sfdc-password: {{ "" | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.salesforce.securityToken }}
  sfdc-security-token: {{ .Values.salesforce.securityToken | b64enc | quote }}
  {{- else }}
  sfdc-security-token: {{ "" | b64enc | quote }}
  {{- end }}
  
  db-user: {{ .Values.postgresql.auth.username | b64enc | quote }}
  db-pass: {{ .Values.postgresql.auth.password | b64enc | quote }}
