apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rag
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-rag
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-rag
    spec:
      containers:
        - name: rag
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            # Inject secrets from postgres-secret
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            # Hardcoded value for DB_HOST and DB_PORT
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"

            # Optional: Append other envs from .Values.env
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            requests:
              memory: "8Gi"
              cpu: "1000m"
            limits:
              memory: "16Gi"
              cpu: "2000m"
          command:
            - gunicorn
          args:
            - "-w"
            - "1"
            - "-b"
            - "0.0.0.0:5000"
            - "--timeout"
            - "300"
            - "rag_app.rag_qa_ui_pgvector_hist:app"
