replicaCount: 1

image:
  repository: sabya610/rag-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  POSTGRES_HOST: "dbhost"
  POSTGRES_DB: "ragdb"
  POSTGRES_USER: "dbuser"
  POSTGRES_PASSWORD: "dbpass"

resources: {}

ingress:
  enabled: false

postgresql:
  enabled: true
  image: postgres:15
  storage: 1Gi
  username: dbuser
  password: dbpass
  database: ragdb
