apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
stringData:
  DB_PASS: {{ .Values.env.DB_PASS | default "postgres" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sfdc-secret
type: Opaque
stringData:
  SF_SID: {{ .Values.sfdc.sessionId | default "" | quote }}
  SFDC_CLIENT_ID: {{ .Values.sfdc.clientId | default "" | quote }}
  SFDC_CLIENT_SECRET: {{ .Values.sfdc.clientSecret | default "" | quote }}
  SFDC_USERNAME: {{ .Values.sfdc.username | default "" | quote }}
  SFDC_PASSWORD: {{ .Values.sfdc.password | default "" | quote }}
  SFDC_SECURITY_TOKEN: {{ .Values.sfdc.securityToken | default "" | quote }}
